### ISSUE TITLE
没有技能编辑器啊

### ISSUE THREAD

**Issue by huise4** [jewer3330/plato#1]

**Comment by jewer3330** [comment]
> _No description provided._

忘了提交了，o(╯□╰)o

**Comment by huise4** [comment]
git上的那个demo有吗。我想看下怎么用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jun.zhao"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午2:07
收件人: "jewer3330/plato"<plato@noreply.github.com&gt;; 
抄送: "灰维空间"<1448901501@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jewer3330/plato] 没有技能编辑器啊 (#1)





  
No description provided.
  
忘了提交了，o(╯□╰)o
